### ISSUE TITLE
does Art need a removeWall method?

### ISSUE THREAD

**Issue by return-string** [MicrowavedScrambledEggs/SWEN222_GroupPage_ArtGame#12]
Are we just removing Walls directly from an Art object's set of walls?

**Comment by mickyscreggs** [comment]
It's for when a player takes a painting that's on multiple walls. It fixes a bug where a player would take a one of these paintings, but the painting would still be on the other walls as well as in the player's inventory.

Check the facebook convo and commit 6c84656 for details

**Comment by kaishuoy** [comment]
i dont think it does because you dont need to remove walls from a art's set of walls. you need to do it the other way around(remove art from a wall) hence each art has a set of walls it appears on to deal with 1 art, 2 walls scenario

**Comment by return-string** [comment]
OK, sweet, just wondering if anything was depending on that! Thanks guys!
