### ISSUE TITLE
Reiker: Screen implementation

### ISSUE THREAD

**Issue by Franimal** [MicrowavedScrambledEggs/SWEN222_GroupPage_ArtGame#5]
If you implement the Screen interface for your renderer I can do the outer window and call your render().  I should be able to put my stuff with that fairly easily then.

**Comment by mootshell** [comment]
I'm not really sure what the purpose of having initialize() in Screen is... Would it make more sense to do that in the constructor?

**Comment by Franimal** [comment]
Yeah I think I'll remove initialize and just have it in the constructor, can't remember any good reason why I used that now.

Also going to remove getWindow and replace it with a static getter in GLWindow.
