### ISSUE TITLE
Stair tiles need a direction

### ISSUE THREAD

**Issue by mickyscreggs** [MicrowavedScrambledEggs/SWEN222_GroupPage_ArtGame#6]
@mootshell @kaishuoy Noticed this when running the debug GUI with the game loading the xml file. Stairs only faced in one direction, which was backwards for some stairs

**Comment by kaishuoy** [comment]
i can add a direction class to stairs, but can you ensure in the level design that a stairs has always got 3 walls around it? ie can only go on to it from the direction the bottom stairs are. tricky to prevent people moving the wrong way on to stairs otherwise

**Comment by mickyscreggs** [comment]
You can totes mount stairs sideways lol. But yeah, indoor stairs usually have handrails blocking your path so I'll put walls around them. Come to think of it they'd need one at least on the other end to stop people mounting stairs from behind

@kaishuoy @mootshell another thing is that stairs will need to know if they are going up or down, as this will affect the way they are rendered

**Comment by kaishuoy** [comment]
oh yea ok i can add a boolean for going down or not as well.
man this whole stairs is a piece of shit lol. we shouldve like made them 'teleporters' and our game futurisitc to make sense. that way like legit 1 simple circle on ground = done

**Comment by mickyscreggs** [comment]
yeah man, who could have known stairs would be so annoying

**Comment by mootshell** [comment]
Whether they're going up or down doesn't really affect rendering as much as the direction does (although I'd only have to rotate them a bit for the direction).
