### ISSUE TITLE
Guards forced to have a patrol?

### ISSUE THREAD

**Issue by mickyscreggs** [MicrowavedScrambledEggs/SWEN222_GroupPage_ArtGame#7]
@kaishuoy  Found out when testing the new parser that can do multiple floors that Guard.offsetPath() throws a GameError when called on a guard without a path (there's one in GroundFloorBasic.xml). For testing I commented it out and got the method to return prematurely instead.

So yeah, do guards have to have paths now?

**Comment by kaishuoy** [comment]
nah guards dont have to have one. was planning to catch the null path in the floor class before calling offsetPath() and forgot about it. seems like issue done since youve changed it to return if null path
